#' Compound Poisson Approximation
#'
#' This function computes the distribution of the number of motif hits
#' that would be observe in a theoretical sequence of length 'L'
#' that is generated by the background model.
#' The distribution can be determine in two alternative ways:
#' 1) We provide a reimplemented version of the algorithm that was
#' described in Pape et al. \emph{Compound poisson approximation
#' of the number of occurrences of a position
#' frequency matrix (PFM) on both strands.} 2008. In contrast to the
#' original model, this implementation can be used with higher-order
#' background models. This version
#' is used with method='pape'.
#' 2) We provide an improved compound Poisson approximation that
#' uses more appropriate statistical assumptions concerning
#' overlapping motif hits and that can be used with higher-order
#' background models as well. The improved version can be used
#' with method='kopp'.
#'
#'
#' @param seqlen Vector of integers that contains the individual sequence
#' lengths of a given set of sequences. This information can be extracted for
#' given DNA sequence of interest using \code{\link{numMotifHits}}.
#' In contrast to \code{\link{combinatorialDist}}, this function
#' supports variable length sequence to be considered.
#' @param overlap Overlapping hit probabilities. This argument is the result of
#' \code{link{probOverlapHit}}, which is essential for both.
#' @param method String that defines which method shall be invoked 'pape' or
#' 'kopp' (see description). Default: method='kopp'
#'
#' @return List containing
#' \describe{
#' \item{dist}{Distribution of the number of hits}
#' }
#' @examples
#'
#'
#' seqfile=system.file("extdata","seq.fasta", package="motifcounter")
#' seqs=Biostrings::readDNAStringSet(seqfile)
#' motiffile=system.file("extdata","x31.tab", package="motifcounter")
#' alpha=0.001
#' gran=0.1
#' motifcounterOption(alpha, gran)
#'
#' # estimate background model from seqfile
#' bg=readBackground(seqs,1)
#'
#' # load motif model from motiffile
#' motif=t(as.matrix(read.table(motiffile)))
#'
#' # compute the distribution for scanning a single DNA strand
#'
#' #Compute overlapping probabilities
#' op=probOverlapHit(motif,bg,singlestranded=TRUE)
#'
#' # Computes the distribution of the number of motif hits
#' seqlen=rep(150,100)
#' dist=compoundPoissonDist(seqlen, op)
#' #plot(1:length(dist$dist)-1, dist$dist)
#'
#' # compute the distribution for scanning both DNA strands
#'
#' #Compute overlapping probabilities
#' op=probOverlapHit(motif,bg,singlestranded=FALSE)
#'
#' # Computes the distribution of the number of motif hits
#' seqlen=rep(150,100)
#' dist=compoundPoissonDist(seqlen, op)
#' #plot(1:length(dist$dist)-1, dist$dist)
#'
#' @seealso \code{\link{combinatorialDist}}
#' @export
compoundPoissonDist=function(seqlen, overlap,method="kopp") {
    overlapValid(overlap)
    # for all practical cases, a maximal clump size of 60
    # should be enough
    maxclumpsize=60
    # determine the max number of hits automatically from the
    # given sequence length.
    # even though it is a little bit of computational overhead,
    # set the maxhits to the total sequence length
    maxhits=sum(seqlen)
    dist=numeric(maxhits+1)
    if (method=="kopp") {
        res=.C("motifcounter_compoundPoisson_useBeta", overlap$alpha,
            overlap$beta, overlap$beta3p, overlap$beta5p,
            as.numeric(dist), as.integer(length(seqlen)),
            as.integer(seqlen),
            as.integer(maxhits), as.integer(maxclumpsize),
            length(overlap$beta),
            as.integer(overlap$singlestranded),PACKAGE="motifcounter")
        dist=res[[5]]
    } else if (method=="pape") {
        if (overlap$singlestranded==TRUE) {
            stop("The Pape et al. implementation of the compound
                Poisson distribution can only be for scanning both DNA strands.
                Use probOverlapHit(singlestranded=F).")
        }
        res=.C("motifcounter_compoundPoissonPape_useGamma", overlap$gamma,
            as.numeric(dist), as.integer(length(seqlen)), as.integer(seqlen),
            as.integer(maxhits), as.integer(maxclumpsize),
            length(overlap$beta),
            PACKAGE="motifcounter")
        dist=res[[2]]
    } else {
        stop("The method must be 'kopp' or 'pape'")
    }
    return (list(dist=dist))
}
