#' Enrichment of motif hits
#' 
#' This function determines whether a given motif is enriched in a given 
#' DNA sequences based on the number of motif hits that would be observed
#' in a random sequence that is generated by the background model. 
#' It can optionally be used based on the 
#' 'compound Poisson approximation' or the 'combinatorial model'.
#' 
#' 
#' @param pfm A position frequency matrix
#' @param sequence Fasta-filename containing the sequence that should
#'      be scanned
#' @param singlestranded Boolean flag that indicates whether one or both
#'      strands are scanned for motif hits
#' @param method String that defines whether to use 
#' the 'compound' Poisson approximation' or the 'combinatorial' model.
#' Default: method='compound'
#'
#' @return P-value for the enrichment test
#' @examples
#' 
#' 
#' seqfile=system.file("extdata","seq.fasta", package="motifcounter")
#' motiffile=system.file("extdata","x31.tab", package="motifcounter")
#' alpha=0.001
#' gran=0.1
#' motifcounterOption(alpha, gran)
#' 
#' # estimate background model from seqfile
#' readBackground(seqfile,1)
#' 
#' # load motif model from motiffile
#' motif=t(as.matrix(read.table(motiffile)))
#' 
#' ### 1 ) Compute the distribution for scanning a *single* DNA strand
#' # based on the 'Compound Poisson model'
#'
#' pvalue=motifEnrichmentTest(motif, 
#'              seqfile,singlestranded=TRUE,method="compound")
#'
#' ### 2 ) Compute the distribution for scanning *both* DNA strand
#' # based on the 'Compound Poisson model'
#'
#' pvalue=motifEnrichmentTest(motif, seqfile,method="compound")
#' 
#' ### 3 ) Compute the distribution for scanning *both* DNA strand
#' # based on the *combinatorial model*
#'
#' pvalue=motifEnrichmentTest(motif, seqfile,singlestranded=FALSE,
#'              method="combinatorial")
#' 
#' @seealso \code{\link{compoundPoissonDist}}, \code{\link{combinatorialDist}}
#' @export
motifEnrichmentTest=function(pfm,sequence,
    singlestranded=FALSE,method="compound") {
    motifValid(pfm)
    #compute overlapping hit probs
    overlap=probOverlapHit(pfm,singlestranded)

    # detemine the number of motif hits
    observations=numMotifHits(pfm,sequence,singlestranded)
    if (method=="compound") {
        dist=compoundPoissonDist(observations$lseq, overlap)
    } else if (method=="combinatorial") {
        dist=combinatorialDist(observations$lseq, overlap)
    }
    if (sum(observations$numofhits)>length(dist$dist)-1) {
        p=0.0;
    } else {
        p=1-sum(dist$dist[1:sum(observations$numofhits)])
    }
    return (p)
}

