#' Enrichment of motif hits
#'
#' This function determines whether a given motif is enriched in a given
#' DNA sequences based on the number of motif hits that would be observed
#' in a random sequence that is generated by the background model.
#' It can optionally be used based on the
#' 'compound Poisson approximation' or the 'combinatorial model'.
#'
#'
#' @param seqs DNAString or DNAStringSet
#' @param pfm A position frequency matrix
#' @param bg A Background object
#' @param singlestranded Boolean flag that indicates whether one or both
#'      strands are scanned for motif hits
#' @param method String that defines whether to use
#' the 'compound' Poisson approximation' or the 'combinatorial' model.
#' Default: method='compound'
#'
#' @return P-value for the enrichment test
#' @examples
#'
#'
#' seqfile=system.file("extdata","seq.fasta", package="motifcounter")
#' seqs=Biostrings::readDNAStringSet(seqfile)
#' motiffile=system.file("extdata","x31.tab", package="motifcounter")
#' alpha=0.001
#' gran=0.1
#' motifcounterOption(alpha, gran)
#'
#' # estimate background model from seqfile
#' bg=readBackground(seqs,1)
#'
#' # load motif model from motiffile
#' motif=t(as.matrix(read.table(motiffile)))
#'
#' ### 1 ) Compute the distribution for scanning a *single* DNA strand
#' # based on the 'Compound Poisson model'
#'
#' pvalue=motifEnrichmentTest(seqs,motif,bg,
#'             singlestranded=TRUE,method="compound")
#'
#' ### 2 ) Compute the distribution for scanning *both* DNA strand
#' # based on the 'Compound Poisson model'
#'
#' pvalue=motifEnrichmentTest(seqs,motif, bg, method="compound")
#'
#' ### 3 ) Compute the distribution for scanning *both* DNA strand
#' # based on the *combinatorial model*
#'
#' pvalue=motifEnrichmentTest(seqs,motif, bg,singlestranded=FALSE,
#'             method="combinatorial")
#'
#' @seealso \code{\link{compoundPoissonDist}}, \code{\link{combinatorialDist}}
#' @export
motifEnrichmentTest=function(seqs, pfm,bg,
    singlestranded=FALSE,method="compound") {
    motifValid(pfm)
    backgroundValid(bg)
    #compute overlapping hit probs
    overlap=probOverlapHit(pfm,bg,singlestranded)

    # detemine the number of motif hits
    observations=numMotifHits(seqs,pfm,bg,singlestranded)
    if (method=="compound") {
        dist=compoundPoissonDist(observations$lseq, overlap)
    } else if (method=="combinatorial") {
        dist=combinatorialDist(observations$lseq, overlap)
    } else {
        stop("method must be 'compound' or 'combinatorial'")
    }
    p=sum(dist$dist[(sum(observations$numofhits)+1):length(dist$dist)])
    return (p)
}
