#' Motif hit enrichment analysis of DNA sequences
#' 
#' The package provides functions for determining the motif hit
#' enrichment for a given position frequency matrix (PFM)
#' in a DNA sequence of interest. 
#' To this end, the user is required to provide 1) a PFM (see
#' \code{link{readMotif}}),
#' 2) a DNA sequence which is used to create 
#' the sequence background model (see \code{link{readBackground}}),
#' and a desired false positive probability of motif hits to occur in 
#' random sequences generated by the background (see \code{\link{mdistOption}}.
#' Based on the PFM and the background model, we analyticly determine
#' the log-likelihood or score distribution, which is used to determine
#' a score threshold that is associated with the desired
#' false positive probability.
#'
#' A motif hit is defined as a position in the sequence at which
#' the observed score is greater or equal than the score threshold.
#' We determine the theoretical distribution of 
#' the number of motif hits that emerge
#' from scanning random DNA sequences that are generated by 
#' the background model in two alternative ways:
#' 1) By a compound Poisson approximation and 2)  by a novel combinatorial
#' model.
#' This example guides you through the main functions that are provided
#' by the package.
#' 
#' @seealso \code{\link{compoundPoissonDist}}, \code{\link{combinatorialDist}}
#' \tabular{ll}{ Package: \tab mdist\cr Type: \tab Package\cr Version: \tab
#' 1.0\cr Date: \tab 2016-11-04\cr License: \tab GPL-2\cr }
#' 
#' @name mdist-package
#' @aliases mdist-package mdist
#' @docType package
#' @author Wolfgang Kopp
#' 
#' Maintainer: Wolfgang Kopp <kopp@@molgen.mpg.de>
#' @keywords PFM, MotifEnrichment
#' @useDynLib mdist, .registration=TRUE
#' @examples
#' 
#' # example input files
#' seqfile=system.file("extdata","seq.fasta", package="mdist")
#' motiffile=system.file("extdata","x31.tab", package="mdist")
#' 
#' # set motif scan options
#' # alpha corresponds to the desired false positive probability
#' # of obtaining a motif hits in a random DNA sequence and is typically
#' # chosen to be 0.01 or lower.
#' alpha=0.01
#' mdistOption(alpha)
#'
#' seqlen=rep(100,1)
#' maxhits=100
#' 
#' # Estimate background model as an order-1 Markov model from seqfile
#' readBackground(seqfile,1)
#' readBackgroundForSampling(seqfile,1) # only used in conjunction with
#' 
#' # Load a PFM model from motiffile and add pseudo-evidence of 0.01
#' # to each element to prevent zero-entry occurrences
#' readMotif(motiffile, 0.01)
#' 
#' # Score distribution is determined analytically using  dynamic programming
#' scoredist=scoreDist()
#' plot(scoredist$score,scoredist$probability, col="green")
#' 
#' 
#' #####
#' # Compute the overlap probabilities with respect to scanning both
#' # DNA strands. They are necessary for the 
#' # distribution of the number of motif hits and the enrichment test
#' op=probOverlapHit(singlestranded=FALSE)
#' 
#' # Compound poisson approximation of the motif hits distribution
#' # in random sequences
#' cpdist=compoundPoissonDist(seqlen, op)
#' 
#' # combinatorial approximation of the motif hits distribution
#' # in random sequences
#' combdist=combinatorialDist(seqlen, op)
#' 
#' #####
#' # Compute the overlap probabilities with respect to scanning both
#' # DNA strands. They are necessary for the 
#' # distribution of the number of motif hits and the enrichment test
#' op=probOverlapHit(singlestranded=TRUE)
#' 
#' # Compound poisson approximation of the motif hits distribution
#' # in random sequences
#' cpdist=compoundPoissonDist(seqlen, op)
#' 
#' # Determine the motif enrichment in a given DNA sequence
#' 
#' # Obtain the number of motif hits in the given sequence
#' numhits=numMotifHits(seqfile,singlestranded=TRUE)
#' op=probOverlapHit(singlestranded=TRUE)
#' pvalue=motifEnrichmentTest(numhits,op,method="compound")
#' 
#' numhits=numMotifHits(seqfile,singlestranded=FALSE)
#' op=probOverlapHit(singlestranded=FALSE)
#' pvalue=motifEnrichmentTest(numhits,op,method="compound")
#' 
#' numhits=numMotifHits(seqfile,singlestranded=FALSE)
#' op=probOverlapHit(singlestranded=FALSE)
#' pvalue=motifEnrichmentTest(numhits,op,method="combinatorial")
#' 
#' 
NULL



